name: bimenc2
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  args: ^2.3.0
  image: ^3.1.1

dev_dependencies:
  lints: ^1.0.0
