name: bimenc2
description: A demonstration of basic text to image encryption
version: 1.0.1

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  args: ^2.3.0
  image: ^3.1.1

dev_dependencies:
  lints: ^1.0.0
